services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://72.60.248.41:8002
    container_name: juditech_frontend
    ports:
      - "3000:3000"
    env_file: []
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_API_URL: http://72.60.248.41:8002
